site_name: triseps
site_url: ""
site_author: Ryou Ohsawa
site_description:
  Source extractoin programs for TriCCS

repo_name: ryou_ohsawa/triseps
repo_url: https://bitbucket.org/ryou_ohsawa/triseps/src/master/
edit_uri: ""

copyright: Copyright &copy; 2023&ndash; Ryou Ohsawa

theme:
  name: 'material'
  favicon: assets/icons/favicon.ico
  logo: assets/icons/android-chrome-512x512.png
  language: 'en'
  font:
    text: Rubik
    code: Source Code Pro
  palette:
    scheme: default
    primary: white
    accent: orange
  features:
    - navigation.sections
    - header.autohide

extra_css:
  - assets/stylesheets/local.css
extra_javascript:
  - assets/javascripts/config_mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - toc:
      toc_depth: 3
  - extra
  - admonition
  - smarty
  - sane_lists
  - meta
  - attr_list
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets:
      check_paths: True
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search

nav:
  - Top Page: index.md
  - Tutorial:
    - 'Overview': tutorial/overview.md
    - tutorial/preparation.md
  - Instrument:
    - inst/overview.md
    - inst/cmos.md
    - inst/header.md
  - Links:
    - bitbucket: https://bitbucket.org/ryou_ohsawa/triseps/src/master/
    - PyPi: https://pypi.org/project/triseps/
