[build-system]
requires = ['setuptools>=61.0.0', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = 'triseps'
description = 'TriCCS Source Exraction Programs'
readme = 'README.md'
requires-python = '>=3.11'
license = {file = 'LICENSE'}
authors = [
  {name = 'Ryou Ohsawa', email = 'ryou.ohsawa@nao.ac.jp'},
]
classifiers = [
  'Development Status :: 3 - Alpha',
  'Intended Audience :: Science/Research',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.11',
  'Programming Language :: Python :: 3.12',
  'Programming Language :: Python :: 3.13',
  'Topic :: Scientific/Engineering :: Astronomy',
]
dynamic = ['version']
dependencies = [
  'astropy>=8.0',
  'numpy>=2.4',
  'astroquery>=0.4.7',
  'photutils>=3.0',
  'scipy>=1.14'
]

[project.urls]
homepage = 'https://github.com/astronasutarou/triseps'
repository = 'https://github.com/astronasutarou/triseps'
documentation = 'https://triseps.readthedocs.io/en/latest/'

[project.scripts]
tripre = 'triseps.bin.tripre:main'
trired = 'triseps.bin.trired:main'
triview = 'triseps.bin.triview:main'
triwcs = 'triseps.bin.triwcs:main'

[project.optional-dependencies]
test = [
  'pytest>=8.3',
  'ruff>=0.16'
]

[tool.setuptools.dynamic]
version = {attr = 'triseps.__version__'}

[tool.setuptools.packages.find]
exclude = ['tests']

[tool.ruff]
line-length = 79
indent-width = 4

[tool.ruff.lint]
select = ['E', 'F', 'W']
ignore = [
  'E221',
  'E401',
  'E701'
]

[tool.ruff.lint.per-file-ignores]
'**/__init__.py' = ['F401']

[tool.ruff.format]
quote-style = 'single'
line-ending = 'lf'
preview = true
